sudo: required
services: 
    - docker

before_install:
    - docker build -t nkwochidubem/docker-react -f Dockerfile.dev .

script:
    - docker run nkwochidubem/docker-react npm run test -- --watchAll=false

deploy:
    - provider: heroku
      api_key: 
        secure: "iooo-4bcb-9ac3-50d0216c4175"
      on: 
        branch: master
      app: docker-react